from .audit import AUDIT_API_DOC
from .dashboard import (
    DASHBOARD_METRICS_API_DOC,
    DASHBOARD_RECENT_ACTIVITY_API_DOC,
)
from .system import SYSTEM_HEALTH_API_DOC, SYSTEM_PING_API_DOC
from .tickets import (
    TICKETS_GET_API_DOC,
    TICKETS_LIST_API_DOC,
    TICKETS_STATUS_GET_API_DOC,
    TICKETS_STATUS_UPDATE_API_DOC,
)

__all__ = [
    "AUDIT_API_DOC",
    "DASHBOARD_METRICS_API_DOC",
    "DASHBOARD_RECENT_ACTIVITY_API_DOC",
    "SYSTEM_HEALTH_API_DOC",
    "SYSTEM_PING_API_DOC",
    "TICKETS_LIST_API_DOC",
    "TICKETS_GET_API_DOC",
    "TICKETS_STATUS_GET_API_DOC",
    "TICKETS_STATUS_UPDATE_API_DOC",
]
